FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && pip install \
    pandas \
    pyarrow \
    boto3 \
    psycopg2-binary \
    jupyterlab \
    python-dotenv \
    sqlalchemy

WORKDIR /app

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
