services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 5s
      timeout: 5s
      retries: 50
    mem_limit: 512m
    networks:
      - suntransit-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 7200000
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx512m"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 5s
      timeout: 5s
      retries: 50
    mem_limit: 1g
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - suntransit-net

  producer-valley-metro:
    build: ./producer
    container_name: producer-valley-metro
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: valley_metro_positions
      GTFS_AGENCY: valley-metro
      GTFS_URL: https://mna.mecatran.com/utw/ws/gtfsfeed/vehicles/valleymetro?apiKey=4f22263f69671d7f49726c3011333e527368211f
    mem_limit: 128m
    networks:
      - suntransit-net

  producer-mbta:
    build: ./producer
    container_name: producer-mbta
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: mbta_positions
      GTFS_AGENCY: mbta-metro
      GTFS_URL: https://cdn.mbta.com/realtime/VehiclePositions.pb
    mem_limit: 128m
    networks:
      - suntransit-net

  spark-master:
    build:
      context: .
      dockerfile: spark-image/Dockerfile
    container_name: spark-master
    hostname: spark-master
    restart: unless-stopped
    depends_on:
      - kafka
      - redis
    volumes:
      - ./spark-jobs:/app
      - ./data:/data:ro
      - ./credentials.env:/app/env/credentials.env:ro
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "spark-master", "--port", "7077", "--webui-port", "8080"]
    environment:
      - HADOOP_USER_NAME=spark
      - REDIS_HOST=suntransit-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=myStrongPassword123
      - POSTGRESQL_URL=jdbc:postgresql://suntransit-postgres:5432/average_delays?user=suntransit&password=suntransit
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:4040:4040"
      - "127.0.0.1:4041:4041"
      - "127.0.0.1:7078:7078"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 3G
    networks:
      - suntransit-net

  spark-worker:
    build:
      context: .
      dockerfile: spark-image/Dockerfile
    restart: unless-stopped
    depends_on:
      - spark-master
      - kafka
      - redis
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077", "--cores", "1", "--memory", "2G"]
    environment:
      - HADOOP_USER_NAME=spark
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    networks:
      - suntransit-net

  postgres:
    image: postgres:17
    container_name: suntransit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: suntransit
      POSTGRES_PASSWORD: suntransit
      POSTGRES_DB: average_delays
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    mem_limit: 512m
    networks:
      - suntransit-net

  redis:
    image: redis/redis-stack:latest
    container_name: suntransit-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
      - "127.0.0.1:8001:8001"
    environment:
      - REDIS_ARGS=--requirepass myStrongPassword123
      - REDISTIMESERIES_ARGS="RETENTION_POLICY=300000"
    mem_limit: 1g
    networks:
      - suntransit-net


  web-app:
    build: ./web-app
    container_name: web-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8082:8082"
    volumes:
      - ./data:/data:ro
    depends_on:
      - redis
      - postgres
    env_file:
      - ./credentials.env
    environment:
      - TIMEZONE=America/Phoenix
      - REDIS_HOST=suntransit-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=myStrongPassword123
      - GTFS_ROOT=/data
      - POSTGRESQL_URL=postgresql+psycopg2://suntransit:suntransit@suntransit-postgres:5432/average_delays
    mem_limit: 512m
    networks:
      - suntransit-net

networks:
  suntransit-net:
    driver: bridge

volumes:
  kafka-data:
  pg-data:
