apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: suntransit
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack:latest
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: REDIS_PASSWORD
            - name: REDIS_ARGS
              value: "--requirepass $(REDIS_PASSWORD)"
            - name: REDISTIMESERIES_ARGS
              value: "RETENTION_POLICY=300000"
          ports:
            - name: redis
              containerPort: 6379
            - name: redisinsight
              containerPort: 8001
          readinessProbe:
            exec:
              command: ["redis-cli", "-a", "$(REDIS_PASSWORD)", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
