apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
  namespace: suntransit
data:
  REDIS_PORT: "6379"
  REDIS_HOST: "redis"
  KAFKA_BROKER: "kafka:9092"
  AWS_REGION: "us-east-2"
  S3_BUCKET: "s3a://suntransit"
  PARQUET_PATH: "s3a://suntransit/stop_times_delay"
  COMPUTE_DELAY: "1"
  COMPUTE_TIMEZONE: "America/Phoenix"
  AGENCY_LIST: "ValleyMetro,MassachusettsBayTransportationAuthority"
