apiVersion: v1
kind: ConfigMap
metadata:
  name: valley-metro-env
  namespace: suntransit
data:
  KAFKA_TOPIC: "valley_metro_positions"
  GTFS_AGENCY: "ValleyMetro"
  REDIS_DB: "0"
  TIMEZONE: "America/Phoenix"
