apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: suntransit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      enableServiceLinks: false
      containers:
        - name: spark-worker
          image: suntransit/spark:latest
          imagePullPolicy: Never
          command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://spark-master:7077
            - --cores
            - "1"
            - --memory
            - "1500M"
          env:
            - name: HADOOP_USER_NAME
              value: spark
          resources:
            requests:
              cpu: "800m"
              memory: "1500Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
